In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
train_data = pd.read_csv("3D Objects/stepic/ssz_data/train.csv")
train_data.head()

id    age  gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  \
0  58036  18387       2     175    75.0    110     70            1     1   
1  88981  23328       2     155    66.0    140     90            1     1   
2  74325  17602       2     168    73.0    120     80            2     1   
3  16519  23432       2     183    95.0    140     90            1     1   
4  28981  23162       1     156    62.0    150     80            1     1   

   smoke  alco  active  cardio  
0      0     0       1       1  
1      1     1       0       0  
2      0     0       1       0  
3      0     0       0       1  
4      0     0       1       1

In [3]:
test_data = pd.read_csv("3D Objects/stepic/ssz_data/test.csv")
test_data.head()

id    age  gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  \
0  36043  17646       2     165    65.0    120     80            1     1   
1  44455  20418       1     161    77.0    120     70            1     1   
2  61323  20347       1     165    88.0    120     80            2     2   
3  27780  18086       2     170    91.0    120     80            3     3   
4  54273  21791       1     158    67.0    130     80            1     1   

   smoke  alco  active  cardio  
0      0     0       0       1  
1      0     0       1       1  
2      0     0       1       1  
3      0     0       1       1  
4      0     0       1       1

In [6]:
train_data.info()
print('\n-------NEXT-------\n')
test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58000 entries, 0 to 57999
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   id           58000 non-null  int64  
 1   age          58000 non-null  int64  
 2   gender       58000 non-null  int64  
 3   height       58000 non-null  int64  
 4   weight       58000 non-null  float64
 5   ap_hi        58000 non-null  int64  
 6   ap_lo        58000 non-null  int64  
 7   cholesterol  58000 non-null  int64  
 8   gluc         58000 non-null  int64  
 9   smoke        58000 non-null  int64  
 10  alco         58000 non-null  int64  
 11  active       58000 non-null  int64  
 12  cardio       58000 non-null  int64  
dtypes: float64(1), int64(12)
memory usage: 5.8 MB

-------NEXT-------

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  ----

In [7]:
x_train = train_data.drop(columns=['cardio'])
y_train = train_data['cardio']

x_test = test_data.drop(columns=['cardio'])
y_test = test_data['cardio']

In [13]:
from sklearn.linear_model import LogisticRegression 

In [22]:
logreg = LogisticRegression(max_iter=150)

In [23]:
logreg.fit(x_train, y_train)

LogisticRegression(max_iter=150)

In [24]:
y_predicted_logreg = logreg.predict(x_test)

In [27]:
x_test.head()

id    age  gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  \
0  36043  17646       2     165    65.0    120     80            1     1   
1  44455  20418       1     161    77.0    120     70            1     1   
2  61323  20347       1     165    88.0    120     80            2     2   
3  27780  18086       2     170    91.0    120     80            3     3   
4  54273  21791       1     158    67.0    130     80            1     1   

   smoke  alco  active  
0      0     0       0  
1      0     0       1  
2      0     0       1  
3      0     0       1  
4      0     0       1

In [25]:
y_predicted_logreg

array([0, 1, 1, ..., 0, 1, 1], dtype=int64)

In [26]:
y_predicted_logreg[:10]

array([0, 1, 1, 0, 1, 1, 0, 0, 1, 0], dtype=int64)

In [29]:
np.array(y_test)[:10]

array([1, 1, 1, 1, 1, 1, 0, 0, 0, 0], dtype=int64)

In [32]:
from sklearn.ensemble import RandomForestClassifier

In [33]:
rf = RandomForestClassifier(n_estimators=20, max_depth=10)

In [34]:
rf.fit(x_train, y_train)

RandomForestClassifier(max_depth=10, n_estimators=20)

In [37]:
y_predicted_rf = rf.predict(x_test)

In [38]:
y_predicted_rf[:10]

array([0, 0, 0, 1, 1, 1, 0, 0, 1, 0], dtype=int64)

In [39]:
np.array(y_test)[:10]

array([1, 1, 1, 1, 1, 1, 0, 0, 0, 0], dtype=int64)

In [40]:
from sklearn.metrics import accuracy_score

In [41]:
accuracy_score(y_predicted_logreg, y_test)

0.6923333333333334

In [42]:
accuracy_score(y_predicted_rf, y_test)

0.7304166666666667

In [43]:
from sklearn.metrics import f1_score

In [44]:
f1_score(y_predicted_logreg, y_test)

0.6837416481069042

In [45]:
f1_score(y_predicted_rf, y_test)

0.7198891678933241